name: GTest

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update APT
      run: sudo apt update
    - name: Install libraries required by GLFW
      run: sudo apt-get install xorg-dev libglu1-mesa-dev
    - name: CMake config
      run: cmake -S ./ -B build/
    - name: CMake build
      run: cmake --build build/
    - name: GTests on CTest
      run: cd build & ctest .
